# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mustar/catkin_ws/src/jupiterobot2_qt/jupiterobot2_qt/scripts/Robot.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1854, 910)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777, 16777))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(330, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(330, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.O5 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.O5.setFont(font)
        self.O5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.O5.setObjectName("O5")
        self.verticalLayout_2.addWidget(self.O5)
        self.O3 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.O3.setFont(font)
        self.O3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.O3.setObjectName("O3")
        self.verticalLayout_2.addWidget(self.O3)
        self.O1 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.O1.setFont(font)
        self.O1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.O1.setObjectName("O1")
        self.verticalLayout_2.addWidget(self.O1)
        self.O6 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.O6.setFont(font)
        self.O6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.O6.setObjectName("O6")
        self.verticalLayout_2.addWidget(self.O6)
        self.O2 = QtWidgets.QPushButton(self.widget_2)
        self.O2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.O2.setFont(font)
        self.O2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.O2.setObjectName("O2")
        self.verticalLayout_2.addWidget(self.O2)
        self.O7 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.O7.setFont(font)
        self.O7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.O7.setObjectName("O7")
        self.verticalLayout_2.addWidget(self.O7)
        self.O2.raise_()
        self.O1.raise_()
        self.O7.raise_()
        self.O5.raise_()
        self.O3.raise_()
        self.O6.raise_()
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.o1 = QtWidgets.QWidget()
        self.o1.setObjectName("o1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.o1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.op1_1 = QtWidgets.QLabel(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.op1_1.sizePolicy().hasHeightForWidth())
        self.op1_1.setSizePolicy(sizePolicy)
        self.op1_1.setMinimumSize(QtCore.QSize(101, 101))
        self.op1_1.setMaximumSize(QtCore.QSize(101, 101))
        self.op1_1.setStyleSheet("background-image: url(:/media/语音合成.png);")
        self.op1_1.setText("")
        self.op1_1.setObjectName("op1_1")
        self.gridLayout_9.addWidget(self.op1_1, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 6, 1, 1, 2)
        self.op1_2 = QtWidgets.QLabel(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.op1_2.sizePolicy().hasHeightForWidth())
        self.op1_2.setSizePolicy(sizePolicy)
        self.op1_2.setMinimumSize(QtCore.QSize(101, 101))
        self.op1_2.setMaximumSize(QtCore.QSize(101, 101))
        self.op1_2.setStyleSheet("\n"
"background-image: url(:/media/语音识别.png);")
        self.op1_2.setText("")
        self.op1_2.setObjectName("op1_2")
        self.gridLayout_9.addWidget(self.op1_2, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 3, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.dele = QtWidgets.QPushButton(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dele.sizePolicy().hasHeightForWidth())
        self.dele.setSizePolicy(sizePolicy)
        self.dele.setMinimumSize(QtCore.QSize(70, 0))
        self.dele.setSizeIncrement(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.dele.setFont(font)
        self.dele.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dele.setObjectName("dele")
        self.gridLayout_11.addWidget(self.dele, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_11.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.for_2 = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.for_2.setFont(font)
        self.for_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.for_2.setObjectName("for_2")
        self.gridLayout_2.addWidget(self.for_2, 1, 12, 1, 1)
        self.who = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.who.setFont(font)
        self.who.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.who.setObjectName("who")
        self.gridLayout_2.addWidget(self.who, 0, 7, 1, 1)
        self.cando = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cando.setFont(font)
        self.cando.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cando.setObjectName("cando")
        self.gridLayout_2.addWidget(self.cando, 2, 13, 1, 1)
        self.ganma = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ganma.setFont(font)
        self.ganma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ganma.setObjectName("ganma")
        self.gridLayout_2.addWidget(self.ganma, 2, 8, 1, 1)
        self.ok = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ok.setFont(font)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setObjectName("ok")
        self.gridLayout_2.addWidget(self.ok, 0, 3, 1, 1)
        self.cause = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cause.setFont(font)
        self.cause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cause.setObjectName("cause")
        self.gridLayout_2.addWidget(self.cause, 2, 4, 1, 1)
        self.do_2 = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.do_2.setFont(font)
        self.do_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.do_2.setObjectName("do_2")
        self.gridLayout_2.addWidget(self.do_2, 0, 15, 1, 1)
        self.know = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.know.setFont(font)
        self.know.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.know.setObjectName("know")
        self.gridLayout_2.addWidget(self.know, 2, 14, 1, 1)
        self.ward = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ward.setFont(font)
        self.ward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ward.setObjectName("ward")
        self.gridLayout_2.addWidget(self.ward, 1, 9, 1, 1)
        self.come = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.come.setFont(font)
        self.come.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.come.setObjectName("come")
        self.gridLayout_2.addWidget(self.come, 1, 15, 1, 1)
        self.de = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.de.setFont(font)
        self.de.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.de.setObjectName("de")
        self.gridLayout_2.addWidget(self.de, 0, 4, 1, 1)
        self.and_2 = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.and_2.setFont(font)
        self.and_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.and_2.setObjectName("and_2")
        self.gridLayout_2.addWidget(self.and_2, 0, 14, 1, 1)
        self.evening = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.evening.setFont(font)
        self.evening.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.evening.setObjectName("evening")
        self.gridLayout_2.addWidget(self.evening, 0, 10, 1, 1)
        self.thank = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thank.setFont(font)
        self.thank.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.thank.setObjectName("thank")
        self.gridLayout_2.addWidget(self.thank, 2, 9, 1, 1)
        self.no = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.no.setFont(font)
        self.no.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.no.setObjectName("no")
        self.gridLayout_2.addWidget(self.no, 1, 2, 1, 1)
        self.at = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.at.setFont(font)
        self.at.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.at.setObjectName("at")
        self.gridLayout_2.addWidget(self.at, 0, 8, 1, 1)
        self.them = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.them.setFont(font)
        self.them.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.them.setObjectName("them")
        self.gridLayout_2.addWidget(self.them, 1, 4, 1, 1)
        self.staff = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.staff.setFont(font)
        self.staff.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.staff.setObjectName("staff")
        self.gridLayout_2.addWidget(self.staff, 2, 16, 1, 1)
        self.bye = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bye.setFont(font)
        self.bye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bye.setObjectName("bye")
        self.gridLayout_2.addWidget(self.bye, 2, 1, 1, 1)
        self.he = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.he.setFont(font)
        self.he.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.he.setObjectName("he")
        self.gridLayout_2.addWidget(self.he, 0, 2, 1, 1)
        self.font = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.font.setFont(font)
        self.font.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.font.setObjectName("font")
        self.gridLayout_2.addWidget(self.font, 1, 10, 1, 1)
        self.down = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.down.setFont(font)
        self.down.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.down.setObjectName("down")
        self.gridLayout_2.addWidget(self.down, 0, 12, 1, 1)
        self.where = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.where.setFont(font)
        self.where.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.where.setObjectName("where")
        self.gridLayout_2.addWidget(self.where, 2, 3, 1, 1)
        self.welcome = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.welcome.setFont(font)
        self.welcome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.welcome.setObjectName("welcome")
        self.gridLayout_2.addWidget(self.welcome, 2, 2, 1, 1)
        self.up = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.up.setFont(font)
        self.up.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.up.setObjectName("up")
        self.gridLayout_2.addWidget(self.up, 0, 11, 1, 1)
        self.so = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.so.setFont(font)
        self.so.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.so.setObjectName("so")
        self.gridLayout_2.addWidget(self.so, 2, 6, 1, 1)
        self.must = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.must.setFont(font)
        self.must.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.must.setObjectName("must")
        self.gridLayout_2.addWidget(self.must, 2, 5, 1, 1)
        self.le = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.le.setFont(font)
        self.le.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.le.setObjectName("le")
        self.gridLayout_2.addWidget(self.le, 1, 3, 1, 1)
        self.what = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.what.setFont(font)
        self.what.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.what.setObjectName("what")
        self.gridLayout_2.addWidget(self.what, 2, 0, 1, 1)
        self.left = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.left.setFont(font)
        self.left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.left.setObjectName("left")
        self.gridLayout_2.addWidget(self.left, 1, 1, 1, 1)
        self.noon = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.noon.setFont(font)
        self.noon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.noon.setObjectName("noon")
        self.gridLayout_2.addWidget(self.noon, 0, 13, 1, 1)
        self.but = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.but.setFont(font)
        self.but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.but.setObjectName("but")
        self.gridLayout_2.addWidget(self.but, 1, 16, 1, 1)
        self.is_2 = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.is_2.setFont(font)
        self.is_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.is_2.setObjectName("is_2")
        self.gridLayout_2.addWidget(self.is_2, 0, 6, 1, 1)
        self.medle = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.medle.setFont(font)
        self.medle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.medle.setObjectName("medle")
        self.gridLayout_2.addWidget(self.medle, 1, 14, 1, 1)
        self.small = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.small.setFont(font)
        self.small.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.small.setObjectName("small")
        self.gridLayout_2.addWidget(self.small, 1, 6, 1, 1)
        self.tell = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tell.setFont(font)
        self.tell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tell.setObjectName("tell")
        self.gridLayout_2.addWidget(self.tell, 2, 10, 1, 1)
        self.go = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.go.setFont(font)
        self.go.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go.setObjectName("go")
        self.gridLayout_2.addWidget(self.go, 0, 16, 1, 1)
        self.single = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.single.setFont(font)
        self.single.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.single.setObjectName("single")
        self.gridLayout_2.addWidget(self.single, 1, 13, 1, 1)
        self.morning = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.morning.setFont(font)
        self.morning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.morning.setObjectName("morning")
        self.gridLayout_2.addWidget(self.morning, 0, 9, 1, 1)
        self.back = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.back.setFont(font)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 1, 11, 1, 1)
        self.please = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.please.setFont(font)
        self.please.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.please.setObjectName("please")
        self.gridLayout_2.addWidget(self.please, 1, 5, 1, 1)
        self.see = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.see.setFont(font)
        self.see.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.see.setObjectName("see")
        self.gridLayout_2.addWidget(self.see, 1, 8, 1, 1)
        self.than = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.than.setFont(font)
        self.than.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.than.setObjectName("than")
        self.gridLayout_2.addWidget(self.than, 2, 11, 1, 1)
        self.right = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.right.setFont(font)
        self.right.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.right.setObjectName("right")
        self.gridLayout_2.addWidget(self.right, 1, 0, 1, 1)
        self.result_2 = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result_2.setFont(font)
        self.result_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.result_2.setObjectName("result_2")
        self.gridLayout_2.addWidget(self.result_2, 2, 15, 1, 1)
        self.ma = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ma.setFont(font)
        self.ma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ma.setObjectName("ma")
        self.gridLayout_2.addWidget(self.ma, 0, 5, 1, 1)
        self.big = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.big.setFont(font)
        self.big.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big.setObjectName("big")
        self.gridLayout_2.addWidget(self.big, 1, 7, 1, 1)
        self.could = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.could.setFont(font)
        self.could.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.could.setObjectName("could")
        self.gridLayout_2.addWidget(self.could, 2, 12, 1, 1)
        self.without = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.without.setFont(font)
        self.without.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.without.setObjectName("without")
        self.gridLayout_2.addWidget(self.without, 2, 7, 1, 1)
        self.you = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.you.setFont(font)
        self.you.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.you.setObjectName("you")
        self.gridLayout_2.addWidget(self.you, 0, 1, 1, 1)
        self.me = QtWidgets.QPushButton(self.o1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.me.setFont(font)
        self.me.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.me.setObjectName("me")
        self.gridLayout_2.addWidget(self.me, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.o1)
        self.label_11.setMaximumSize(QtCore.QSize(1104, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 6, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 1, 4, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.o1_1 = QtWidgets.QPushButton(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o1_1.sizePolicy().hasHeightForWidth())
        self.o1_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.o1_1.setFont(font)
        self.o1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o1_1.setObjectName("o1_1")
        self.horizontalLayout_10.addWidget(self.o1_1)
        spacerItem5 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout_9.addLayout(self.horizontalLayout_10, 2, 3, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.o1_2 = QtWidgets.QPushButton(self.o1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o1_2.sizePolicy().hasHeightForWidth())
        self.o1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.o1_2.setFont(font)
        self.o1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o1_2.setObjectName("o1_2")
        self.horizontalLayout_11.addWidget(self.o1_2)
        spacerItem6 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.gridLayout_9.addLayout(self.horizontalLayout_11, 5, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_9, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.o1)
        self.o2 = QtWidgets.QWidget()
        self.o2.setObjectName("o2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.o2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.arm_show = QtWidgets.QLabel(self.o2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arm_show.sizePolicy().hasHeightForWidth())
        self.arm_show.setSizePolicy(sizePolicy)
        self.arm_show.setText("")
        self.arm_show.setObjectName("arm_show")
        self.gridLayout_16.addWidget(self.arm_show, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arm_play_stop = QtWidgets.QPushButton(self.o2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arm_play_stop.sizePolicy().hasHeightForWidth())
        self.arm_play_stop.setSizePolicy(sizePolicy)
        self.arm_play_stop.setMinimumSize(QtCore.QSize(80, 70))
        self.arm_play_stop.setMaximumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.arm_play_stop.setFont(font)
        self.arm_play_stop.setObjectName("arm_play_stop")
        self.horizontalLayout_2.addWidget(self.arm_play_stop)
        self.gridLayout_16.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.o2)
        self.o3 = QtWidgets.QWidget()
        self.o3.setObjectName("o3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.o3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem7, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.gridLayout_15.addLayout(self.verticalLayout_6, 2, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.o3)
        self.label_15.setMinimumSize(QtCore.QSize(101, 101))
        self.label_15.setMaximumSize(QtCore.QSize(101, 101))
        self.label_15.setStyleSheet("background-image: url(:/media/人脸识别.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 5, 1, 1, 1)
        self.op3_2 = QtWidgets.QLabel(self.o3)
        self.op3_2.setMinimumSize(QtCore.QSize(101, 101))
        self.op3_2.setMaximumSize(QtCore.QSize(101, 101))
        self.op3_2.setStyleSheet("background-image: url(:/media/人脸检测.png);")
        self.op3_2.setText("")
        self.op3_2.setObjectName("op3_2")
        self.gridLayout_15.addWidget(self.op3_2, 3, 1, 1, 1)
        self.o3_6_3 = QtWidgets.QPushButton(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o3_6_3.sizePolicy().hasHeightForWidth())
        self.o3_6_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.o3_6_3.setFont(font)
        self.o3_6_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o3_6_3.setObjectName("o3_6_3")
        self.gridLayout_15.addWidget(self.o3_6_3, 5, 6, 1, 1)
        self.face_real = QtWidgets.QPushButton(self.o3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.face_real.setFont(font)
        self.face_real.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.face_real.setObjectName("face_real")
        self.gridLayout_15.addWidget(self.face_real, 3, 6, 1, 1)
        self.op3_4 = QtWidgets.QLabel(self.o3)
        self.op3_4.setMinimumSize(QtCore.QSize(101, 101))
        self.op3_4.setMaximumSize(QtCore.QSize(101, 101))
        self.op3_4.setStyleSheet("background-image: url(:/media/pose.png);")
        self.op3_4.setText("")
        self.op3_4.setObjectName("op3_4")
        self.gridLayout_15.addWidget(self.op3_4, 7, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem9, 6, 1, 1, 1)
        self.o3_1 = QtWidgets.QPushButton(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o3_1.sizePolicy().hasHeightForWidth())
        self.o3_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(30)
        self.o3_1.setFont(font)
        self.o3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o3_1.setObjectName("o3_1")
        self.gridLayout_15.addWidget(self.o3_1, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.o3)
        self.label_14.setMinimumSize(QtCore.QSize(101, 101))
        self.label_14.setMaximumSize(QtCore.QSize(101, 101))
        self.label_14.setStyleSheet("background-image: url(:/media/人脸真伪.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 3, 5, 1, 1)
        self.op3_1 = QtWidgets.QLabel(self.o3)
        self.op3_1.setMinimumSize(QtCore.QSize(101, 101))
        self.op3_1.setMaximumSize(QtCore.QSize(101, 101))
        self.op3_1.setStyleSheet("background-image: url(:/media/目标跟踪.png);")
        self.op3_1.setText("")
        self.op3_1.setObjectName("op3_1")
        self.gridLayout_15.addWidget(self.op3_1, 0, 1, 1, 1)
        self.face_recongnize = QtWidgets.QPushButton(self.o3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.face_recongnize.setFont(font)
        self.face_recongnize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.face_recongnize.setObjectName("face_recongnize")
        self.gridLayout_15.addWidget(self.face_recongnize, 5, 3, 1, 1)
        self.o3_6_2 = QtWidgets.QPushButton(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o3_6_2.sizePolicy().hasHeightForWidth())
        self.o3_6_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.o3_6_2.setFont(font)
        self.o3_6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o3_6_2.setObjectName("o3_6_2")
        self.gridLayout_15.addWidget(self.o3_6_2, 7, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.gridLayout_15.addLayout(self.verticalLayout_4, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.o3)
        self.label_4.setMinimumSize(QtCore.QSize(101, 101))
        self.label_4.setMaximumSize(QtCore.QSize(101, 101))
        self.label_4.setStyleSheet("background-image: url(:/media/mask.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 5, 5, 1, 1)
        self.o3_6_4 = QtWidgets.QPushButton(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o3_6_4.sizePolicy().hasHeightForWidth())
        self.o3_6_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.o3_6_4.setFont(font)
        self.o3_6_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o3_6_4.setObjectName("o3_6_4")
        self.gridLayout_15.addWidget(self.o3_6_4, 7, 6, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem11, 0, 7, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem12, 2, 1, 1, 1)
        self.o3_5 = QtWidgets.QPushButton(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o3_5.sizePolicy().hasHeightForWidth())
        self.o3_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.o3_5.setFont(font)
        self.o3_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o3_5.setObjectName("o3_5")
        self.gridLayout_15.addWidget(self.o3_5, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.o3)
        self.label_6.setMinimumSize(QtCore.QSize(101, 101))
        self.label_6.setMaximumSize(QtCore.QSize(101, 101))
        self.label_6.setStyleSheet("background-image: url(:/media/hand_detect.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 7, 1, 1, 1)
        self.o3_6_1 = QtWidgets.QPushButton(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o3_6_1.sizePolicy().hasHeightForWidth())
        self.o3_6_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.o3_6_1.setFont(font)
        self.o3_6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o3_6_1.setObjectName("o3_6_1")
        self.gridLayout_15.addWidget(self.o3_6_1, 3, 3, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.o3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem13)
        self.gridLayout_15.addLayout(self.verticalLayout_7, 6, 3, 1, 1)
        self.op3_5 = QtWidgets.QLabel(self.o3)
        self.op3_5.setMinimumSize(QtCore.QSize(101, 101))
        self.op3_5.setMaximumSize(QtCore.QSize(101, 101))
        self.op3_5.setStyleSheet("background-image: url(:/media/yolo.png);")
        self.op3_5.setText("")
        self.op3_5.setObjectName("op3_5")
        self.gridLayout_15.addWidget(self.op3_5, 0, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem14, 4, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem15, 8, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_15, 2, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.o3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 59))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 6, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem16, 0, 6, 1, 1)
        self.stackedWidget.addWidget(self.o3)
        self.o4 = QtWidgets.QWidget()
        self.o4.setObjectName("o4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.o4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nav_play_stop = QtWidgets.QPushButton(self.o4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_play_stop.sizePolicy().hasHeightForWidth())
        self.nav_play_stop.setSizePolicy(sizePolicy)
        self.nav_play_stop.setMinimumSize(QtCore.QSize(80, 70))
        self.nav_play_stop.setMaximumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nav_play_stop.setFont(font)
        self.nav_play_stop.setObjectName("nav_play_stop")
        self.horizontalLayout_4.addWidget(self.nav_play_stop)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.nav_show = QtWidgets.QLabel(self.o4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_show.sizePolicy().hasHeightForWidth())
        self.nav_show.setSizePolicy(sizePolicy)
        self.nav_show.setText("")
        self.nav_show.setObjectName("nav_show")
        self.horizontalLayout_5.addWidget(self.nav_show)
        self.gridLayout_12.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.o4)
        self.o5 = QtWidgets.QWidget()
        self.o5.setObjectName("o5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.o5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.o5)
        self.label_9.setMinimumSize(QtCore.QSize(101, 101))
        self.label_9.setMaximumSize(QtCore.QSize(101, 101))
        self.label_9.setStyleSheet("background-image: url(:/media/qwen_img.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 1, 5, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.o5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        self.qwen_in = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_in.sizePolicy().hasHeightForWidth())
        self.qwen_in.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.qwen_in.setFont(font)
        self.qwen_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qwen_in.setObjectName("qwen_in")
        self.verticalLayout_5.addWidget(self.qwen_in)
        self.qwen_play = QtWidgets.QPushButton(self.page_2)
        self.qwen_play.setMinimumSize(QtCore.QSize(0, 67))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qwen_play.setFont(font)
        self.qwen_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qwen_play.setObjectName("qwen_play")
        self.verticalLayout_5.addWidget(self.qwen_play)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem19)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1135, 653))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.qwen_out = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_out.sizePolicy().hasHeightForWidth())
        self.qwen_out.setSizePolicy(sizePolicy)
        self.qwen_out.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.qwen_out.setFont(font)
        self.qwen_out.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.qwen_out.setWordWrap(True)
        self.qwen_out.setObjectName("qwen_out")
        self.horizontalLayout_12.addWidget(self.qwen_out)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem20, 2, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem21, 1, 1, 1, 1)
        self.qwen_img_in = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_img_in.sizePolicy().hasHeightForWidth())
        self.qwen_img_in.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.qwen_img_in.setFont(font)
        self.qwen_img_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qwen_img_in.setObjectName("qwen_img_in")
        self.gridLayout_13.addWidget(self.qwen_img_in, 1, 2, 1, 1)
        self.qwen_img_show = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_img_show.sizePolicy().hasHeightForWidth())
        self.qwen_img_show.setSizePolicy(sizePolicy)
        self.qwen_img_show.setMinimumSize(QtCore.QSize(640, 480))
        self.qwen_img_show.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qwen_img_show.setFont(font)
        self.qwen_img_show.setText("")
        self.qwen_img_show.setObjectName("qwen_img_show")
        self.gridLayout_13.addWidget(self.qwen_img_show, 0, 1, 1, 4)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem22, 1, 4, 1, 1)
        self.qwen_img_play = QtWidgets.QPushButton(self.page_3)
        self.qwen_img_play.setMinimumSize(QtCore.QSize(0, 67))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qwen_img_play.setFont(font)
        self.qwen_img_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qwen_img_play.setObjectName("qwen_img_play")
        self.gridLayout_13.addWidget(self.qwen_img_play, 1, 3, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 3, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem23, 4, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 142, 422))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.qwen_img_out = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_img_out.sizePolicy().hasHeightForWidth())
        self.qwen_img_out.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qwen_img_out.setFont(font)
        self.qwen_img_out.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.qwen_img_out.setWordWrap(True)
        self.qwen_img_out.setObjectName("qwen_img_out")
        self.horizontalLayout_14.addWidget(self.qwen_img_out)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_14.addWidget(self.scrollArea_2, 0, 1, 5, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.gridLayout_5.addWidget(self.stackedWidget_2, 2, 0, 1, 8)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem24, 0, 3, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem25, 1, 0, 1, 1)
        self.op5_2 = QtWidgets.QLabel(self.o5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.op5_2.sizePolicy().hasHeightForWidth())
        self.op5_2.setSizePolicy(sizePolicy)
        self.op5_2.setMinimumSize(QtCore.QSize(101, 101))
        self.op5_2.setMaximumSize(QtCore.QSize(101, 101))
        self.op5_2.setStyleSheet("background-image: url(:/media/llm.png);")
        self.op5_2.setText("")
        self.op5_2.setObjectName("op5_2")
        self.gridLayout_5.addWidget(self.op5_2, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem26, 3, 2, 1, 1)
        self.qwen_chat = QtWidgets.QPushButton(self.o5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_chat.sizePolicy().hasHeightForWidth())
        self.qwen_chat.setSizePolicy(sizePolicy)
        self.qwen_chat.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.qwen_chat.setFont(font)
        self.qwen_chat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qwen_chat.setObjectName("qwen_chat")
        self.gridLayout_5.addWidget(self.qwen_chat, 1, 2, 1, 1)
        self.qwen_img = QtWidgets.QPushButton(self.o5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwen_img.sizePolicy().hasHeightForWidth())
        self.qwen_img.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.qwen_img.setFont(font)
        self.qwen_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qwen_img.setObjectName("qwen_img")
        self.gridLayout_5.addWidget(self.qwen_img, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.o5)
        self.o6 = QtWidgets.QWidget()
        self.o6.setObjectName("o6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.o6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.o6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_8.addItem(spacerItem27)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.o6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 5, 2, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem28, 6, 2, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem29, 2, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem30, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.o6)
        self.label_3.setMinimumSize(QtCore.QSize(101, 101))
        self.label_3.setMaximumSize(QtCore.QSize(101, 101))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setStyleSheet("background-image: url(:/media/手绘.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem31)
        self.label_7 = QtWidgets.QLabel(self.o6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.o6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(51)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(101, 101))
        self.label.setMaximumSize(QtCore.QSize(101, 101))
        self.label.setStyleSheet("background-image: url(:/media/举手.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 1, 1, 1)
        self.pose_turlte = QtWidgets.QPushButton(self.o6)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pose_turlte.setFont(font)
        self.pose_turlte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pose_turlte.setObjectName("pose_turlte")
        self.gridLayout_4.addWidget(self.pose_turlte, 4, 2, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 2, 3, 1, 1)
        self.o6_1 = QtWidgets.QPushButton(self.o6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o6_1.sizePolicy().hasHeightForWidth())
        self.o6_1.setSizePolicy(sizePolicy)
        self.o6_1.setMinimumSize(QtCore.QSize(0, 0))
        self.o6_1.setMaximumSize(QtCore.QSize(167777, 1677777))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.o6_1.setFont(font)
        self.o6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.o6_1.setObjectName("o6_1")
        self.gridLayout_4.addWidget(self.o6_1, 2, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 2, 1)
        self.stackedWidget.addWidget(self.o6)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionRos1 = QtWidgets.QAction(MainWindow)
        self.actionRos1.setObjectName("actionRos1")
        self.actionRos2 = QtWidgets.QAction(MainWindow)
        self.actionRos2.setObjectName("actionRos2")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.O5.setText(_translate("MainWindow", "LLM Interaction"))
        self.O3.setText(_translate("MainWindow", "Computer Vision"))
        self.O1.setText(_translate("MainWindow", "Speech Interaction"))
        self.O6.setText(_translate("MainWindow", "HRI"))
        self.O2.setText(_translate("MainWindow", "Robot Arm"))
        self.O7.setText(_translate("MainWindow", "Navigation"))
        self.label_10.setText(_translate("MainWindow", "Speech Recognition"))
        self.label_2.setText(_translate("MainWindow", "Speech Synthesis"))
        self.dele.setText(_translate("MainWindow", "⌫"))
        self.for_2.setText(_translate("MainWindow", "为"))
        self.who.setText(_translate("MainWindow", "谁"))
        self.cando.setText(_translate("MainWindow", "能够"))
        self.ganma.setText(_translate("MainWindow", "干嘛"))
        self.ok.setText(_translate("MainWindow", "好"))
        self.cause.setText(_translate("MainWindow", "因为"))
        self.do_2.setText(_translate("MainWindow", "做"))
        self.know.setText(_translate("MainWindow", "知道"))
        self.ward.setText(_translate("MainWindow", "向"))
        self.come.setText(_translate("MainWindow", "来"))
        self.de.setText(_translate("MainWindow", "的"))
        self.and_2.setText(_translate("MainWindow", "和"))
        self.evening.setText(_translate("MainWindow", "晚"))
        self.thank.setText(_translate("MainWindow", "谢谢"))
        self.no.setText(_translate("MainWindow", "不"))
        self.at.setText(_translate("MainWindow", "在"))
        self.them.setText(_translate("MainWindow", "们"))
        self.staff.setText(_translate("MainWindow", "东西"))
        self.bye.setText(_translate("MainWindow", "再见"))
        self.he.setText(_translate("MainWindow", "他"))
        self.font.setText(_translate("MainWindow", "前"))
        self.down.setText(_translate("MainWindow", "下"))
        self.where.setText(_translate("MainWindow", "哪里"))
        self.welcome.setText(_translate("MainWindow", "客气"))
        self.up.setText(_translate("MainWindow", "上"))
        self.so.setText(_translate("MainWindow", "所以"))
        self.must.setText(_translate("MainWindow", "必须"))
        self.le.setText(_translate("MainWindow", "了"))
        self.what.setText(_translate("MainWindow", "什么"))
        self.left.setText(_translate("MainWindow", "左"))
        self.noon.setText(_translate("MainWindow", "午"))
        self.but.setText(_translate("MainWindow", "但"))
        self.is_2.setText(_translate("MainWindow", "是"))
        self.medle.setText(_translate("MainWindow", "中"))
        self.small.setText(_translate("MainWindow", "小"))
        self.tell.setText(_translate("MainWindow", "告诉"))
        self.go.setText(_translate("MainWindow", "去"))
        self.single.setText(_translate("MainWindow", "个"))
        self.morning.setText(_translate("MainWindow", "早"))
        self.back.setText(_translate("MainWindow", "后"))
        self.please.setText(_translate("MainWindow", "请"))
        self.see.setText(_translate("MainWindow", "看"))
        self.than.setText(_translate("MainWindow", "然后"))
        self.right.setText(_translate("MainWindow", "右"))
        self.result_2.setText(_translate("MainWindow", "结果"))
        self.ma.setText(_translate("MainWindow", "吗"))
        self.big.setText(_translate("MainWindow", "大"))
        self.could.setText(_translate("MainWindow", "可以"))
        self.without.setText(_translate("MainWindow", "没有"))
        self.you.setText(_translate("MainWindow", "你"))
        self.me.setText(_translate("MainWindow", "我"))
        self.o1_1.setText(_translate("MainWindow", "Speech Synthesis"))
        self.o1_2.setText(_translate("MainWindow", "Speech Recognition"))
        self.arm_play_stop.setText(_translate("MainWindow", "❚❚"))
        self.label_13.setText(_translate("MainWindow", "YOLO object recognition requires longer time to load, please wait patiently..."))
        self.o3_6_3.setText(_translate("MainWindow", "Face Landmark Detection"))
        self.face_real.setText(_translate("MainWindow", "Face Detection"))
        self.o3_1.setText(_translate("MainWindow", "Color Tracking"))
        self.face_recongnize.setText(_translate("MainWindow", "Face Recognition"))
        self.o3_6_2.setText(_translate("MainWindow", "Hand Joint Detection"))
        self.label_12.setText(_translate("MainWindow", "Operation Guide: After starting, use the mouse to select the color to be tracked in the picture."))
        self.o3_6_4.setText(_translate("MainWindow", "Body Joint Detection"))
        self.o3_5.setText(_translate("MainWindow", "YOLO Object Detection"))
        self.o3_6_1.setText(_translate("MainWindow", "Frontal Face Detection"))
        self.label_16.setText(_translate("MainWindow", "Enter the name in the input box, press Enter to start taking pictures, press y to take a picture, take about 5 pictures and press n to save.\n"
""))
        self.label_5.setText(_translate("MainWindow", "     Loading...         "))
        self.nav_play_stop.setText(_translate("MainWindow", "❚❚"))
        self.qwen_in.setText(_translate("MainWindow", "  Ask a Question  "))
        self.qwen_play.setText(_translate("MainWindow", "Waiting for result..."))
        self.qwen_out.setText(_translate("MainWindow", "Please click the \"Ask a Question\" button to start Q and A with LLM."))
        self.qwen_img_in.setText(_translate("MainWindow", "  Ask a Question  "))
        self.qwen_img_play.setText(_translate("MainWindow", "Waiting for result..."))
        self.qwen_img_out.setText(_translate("MainWindow", "Please click the \"Ask a Question\" button to start Q and A with LLM. For example: Describe the scene you see."))
        self.qwen_chat.setText(_translate("MainWindow", "  Q and A with LLM  "))
        self.qwen_img.setText(_translate("MainWindow", "Vision-Text with VLM"))
        self.label_8.setText(_translate("MainWindow", "Click the button, raise your right hand and spread your fingers to start the countdown to take pictures."))
        self.label_17.setText(_translate("MainWindow", "Once opened, move the windows to avoid overlap. Use your right forearm to control the turtle\'s movement. Raising your elbow above your shoulder will create a special effect!\n"
""))
        self.label_7.setText(_translate("MainWindow", "Loading..."))
        self.pose_turlte.setText(_translate("MainWindow", "Gesture Control of a Little Turtle"))
        self.o6_1.setText(_translate("MainWindow", "     Gesture Photo Taking     "))
        self.actionRos1.setText(_translate("MainWindow", "Ros1"))
        self.actionRos2.setText(_translate("MainWindow", "Ros2"))
import imgs.imgs_rc
